# -*- coding: utf-8 -*-
"""Gait Data Collection Pipeline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UDVGs3SN83yxnANzD--pdT03JjbmXLZb
"""

from diagrams import Diagram, Node, Cluster, Edge
from diagrams.azure.general import Usericon
from urllib.request import urlretrieve
from diagrams.aws.general import User
from diagrams.programming.language import Python
from diagrams.generic.database import SQL
from diagrams.custom import Custom

# Set up the global diagrams context using the Diagram class
with Diagram("Gait Data Collection Pipeline", show=False, direction="LR", outformat="png") as show:

    # Create nodes
    user = User("Data collection\nfrom participants")


    # Create clusters
    with Cluster("Laboratory set-up"):
        vicon_URL = "https://logemas.com/wp-content/uploads/2020/04/Copy-of-VICON_Logo_NEW_light-blue-1-1-1.png"
        vicon_icon_path = "vicon.png"
        urlretrieve(vicon_URL, vicon_icon_path)
        vicon = Custom("Motion Capture \nSystem",vicon_icon_path, edge_label="Motion Capture System", fontsize="12")

    with Cluster("Data Pre-processing"):
      python = Python("Data Labelling")


    with Cluster("Database"):
      SQL = SQL("Data")

    # Create edges to connect nodes
    user >> vicon
    vicon >> python
    python >> SQL

show